@startuml
class Usuario{
    estado : Estado
    nombre: String
    apellido : String
    edad : Integer
    sexo : Sexo
    direccion : Direccion
    + configurarEstrategiaAnteIncidente(EstrategiaAnteIncidente) : void
}

enum Sexo{
    Masculino
    Femenino
    Otro
}

interface Estado{
    'TODO: Que metodo podria ir en esta interfaz??'
}

class Transeunte {
    accionAnteIncidente : EstrategiaAnteIncidente

    + generarViaje() : Viaje
    - definirCuidador(candidatos : List<Usuario>) : void
    + comenzarViaje(Viaje) : void
    + llegueBien(Viaje) : void
}

class Cuidador {
    + confirmarCuidado(Viaje) : void
    - aceptarCuidado(Viaje) : void
    - rechazarCuidado(Viaje) : void
}

class Viaje {
    ruta: Ruta
    estado : EstadoViaje
    + comenzar() : void
    + finalizar() : void
}

enum EstadoViaje{
    EN_CURSO
    FINALIZADO
}

class Ruta{
    inicio : Direccion
    paradas : List<Parada>
    duracion : Integer
    seguimiento : EstrategiaSeguimiento
    + calcularDuracion() : Integer
}

class Parada {
    direccion : Direccion
    TiempoDemora : Integer
}

interface EstrategiaSeguimiento {
    seguir()
}

class SeguimientoPorNotificacionLlegada implements EstrategiaSeguimiento {
    + notificarLlegada(nroParada : Integer) : void
}

class SeguimientoPorTiempoParada implements EstrategiaSeguimiento {
    + definirTiempoPorParada() : void
}

interface EstrategiaAnteIncidente {
    ejecutarEstrategia() : void
}

class NotificarCuidador{}

class NotificarPolicia{}

class NotificarCelular{}

'TODO: Checkear si estan bien parametrizados los minutos'
class Esperar{
    - esperar(minutos : Integer)
}

class Direccion{
    calle : String
    codigoPostal : String
    altura : String
}

'Relaciones'
Usuario *-- Estado
Usuario o-- Direccion
Usuario o-- EstrategiaAnteIncidente
Usuario -- Sexo

Estado <|.. Transeunte
Estado <|.. Cuidador

Transeunte *-- EstrategiaAnteIncidente

Viaje o-- Ruta
Transeunte o-- Viaje
Cuidador o-- Viaje
Viaje -- EstadoViaje
Viaje *-- EstrategiaSeguimiento

Ruta o-- Direccion

EstrategiaAnteIncidente <|.. NotificarCuidador
EstrategiaAnteIncidente <|.. NotificarCelular
EstrategiaAnteIncidente <|.. NotificarPolicia
EstrategiaAnteIncidente <|.. Esperar

'Notas'
note left of EstrategiaSeguimiento
    Implementacion del patron
    **Strategy** para que un usuario
    pueda elegir como seguir un viaje.
end note

note left of Estado
    Implementacion del patron
    **State** para un usuario
    transeunte o cuidador.
end note

note left of EstrategiaAnteIncidente
    Implementacion del patron
    **Strategy** para que un usuario
    pueda elegir como actuar ante
    un incidente.
end note

@enduml