@startuml
class Usuario{
    nombre: String
    apellido : String
    edad : Integer
    sexo : Sexo
    direccion : Direccion
}

class UsuarioPasivo extends Usuario {
    + confirmarCuidado(Viaje) : bool
    - aceptarCuidado(Viaje) : void
    - rechazarCuidado(Viaje) : void
}

class UsuarioActivo extends UsuarioPasivo {
    accionAnteIncidente : EstrategiaAnteIncidente

    + solicitarViaje() : Viaje
    + comenzarViaje() : Viaje
    + seleccionarCuidador(List<UsuarioPasivo>)
    + confirmarCuidado(Viaje)
    + llegueBien(Viaje)
    - solicitarAcompañamiento() : void
}

enum Sexo{
    Masculino
    Femenino
    Otro
}

class Viaje {
    ruta: Ruta
    estado : EstadoViaje
    cuidador : Usuario
    transeunte : Usuario
    + comenzar() : void
    + finalizar() : void
}

enum EstadoViaje{
    EN_CURSO
    FINALIZADO
}

class Ruta{
    inicio : Direccion
    paradas : List<Parada>
    duracion : Integer
    seguimiento : EstrategiaSeguimiento
    + calcularDuracion() : Integer
}

class Parada {
    direccion : Direccion
    tiempoDemora : Integer
}

interface EstrategiaSeguimiento {
    calcularDemora(List<Parada>)
}

class SeguimientoPorNotificacionLlegada implements EstrategiaSeguimiento {
    + notificarLlegada(nroParada : Integer) : void
}

class SeguimientoPorTiempoParada implements EstrategiaSeguimiento {
    - demoraPorTramo(paradaA : Direccion, paradaB : Direccion) : Integer
}

interface EstrategiaAnteIncidente {
    ejecutarEstrategia() : void
}

class NotificarCuidadores{}

class NotificarPolicia{}

class NotificarCelular{}

class Esperar{
    - esperar(minutos : Integer)
}

class Direccion{
    calle : String
    codigoPostal : String
    altura : String
}

'Relaciones'
Usuario o-- Direccion
Usuario -- Sexo

UsuarioActivo *-- EstrategiaAnteIncidente
UsuarioActivo o-- Viaje

UsuarioPasivo o-- Viaje

Viaje o-- Ruta
Viaje -- EstadoViaje

Ruta o-- Parada
Ruta *-- EstrategiaSeguimiento
Ruta o-- Direccion

EstrategiaAnteIncidente <|.. NotificarCuidadores
EstrategiaAnteIncidente <|.. NotificarCelular
EstrategiaAnteIncidente <|.. NotificarPolicia
EstrategiaAnteIncidente <|.. Esperar

'Notas'
note right of EstrategiaSeguimiento
    Implementacion del patron
    **Strategy** para que un usuario
    pueda elegir como seguir un viaje.
end note

note left of EstrategiaAnteIncidente
    Implementacion del patron
    **Strategy** para que un usuario
    pueda elegir como actuar ante
    un incidente.
end note

@enduml