@startuml
class Usuario{
    tipo : TipoUsuario
    nombre: String
    apellido : String
    edad : Integer
    genero : String
    direccion : Direccion
}

interface TipoUsuario{
    comenzarViaje()
    finalizarViaje()
}

class Transeunte {
    accionAnteIncidente : EstrategiaAnteIncidente

    + seleccionarCuidador([]Usuario)
    - llegueBien()
}

class Cuidador {
    - aceptarCuidado()
    - rechazarCuidado()
}

class Ruta{
    inicio : Direccion
    fin : Direccion
    duracion : Integer
}

'Mediante esta interfaz se implementa el patron strategy para la reaccion ante incidentes'
interface EstrategiaAnteIncidente {
    ejecutarEstrategia()
}

class NotificarCuidador{}

class NotificarPolicia{}

class NotificarCelular{}

'TODO: Checkear si estan bien parametrizados los minutos'
class Esperar{
    - esperar(minutos : Integer)
}

class Direccion{
    calle : String
    codigoPostal : String
    altura : String
}

Usuario *-- TipoUsuario
Usuario o-- Direccion

TipoUsuario <|.. Transeunte
TipoUsuario <|.. Cuidador

Transeunte *-- EstrategiaAnteIncidente

Ruta o-- Direccion

EstrategiaAnteIncidente <|.. NotificarCuidador
EstrategiaAnteIncidente <|.. NotificarCelular
EstrategiaAnteIncidente <|.. NotificarPolicia
EstrategiaAnteIncidente <|.. Esperar

@enduml